### ISSUE TITLE
Extension not functioning on latest Chrome on Mac OS Ventura M1

### ISSUE THREAD

**Issue by 10bn** [SethuSenthil/Copy-for-ChatGPT#11]
<img width="1326" alt="Screenshot 2023-04-06 at 15 37 33" src="https://user-images.githubusercontent.com/46263124/230395420-9fde8c37-ed4f-49d5-8b0f-a001e0e1d11b.png">
<img width="906" alt="Screenshot 2023-04-06 at 15 37 01" src="https://user-images.githubusercontent.com/46263124/230395432-20864698-b37b-4912-bf43-5f98c3166f52.png">

Hey There, thanks for the great plugin, unfortunately it dosen't work for me. 

Anything I should try to make it work?

**Comment by SethuSenthil** [comment]
Thanks for reporting this issue! The latest update ( a2076fe868f3a5b8639c2603277bfd0183ae6c59 )should fix this issue!  
Keep in mind it is still in review on the Google Chrome Extention store so you might not get the option to update through the store for a few hours until they approve the update.
