### ISSUE TITLE
Idea how to solve the always changing Format of OpenAIs Front end.

### ISSUE THREAD

**Issue by SirNoName2705** [SethuSenthil/Copy-for-ChatGPT#14]
Right now, I think, you are trying to recognize the Structure of the written HTML and then copy the inner HTML recursively, right?

I think another way to solve this, is, to capture a Screenshot of the given block and then run an OCR over it. With that in place, you would not need to change this part of the code, and you can also maybe recognize Katex Symbols.

**Comment by SethuSenthil** [comment]
Hi there!

Thank you for taking the time to share your idea with us. While I appreciate your suggestion of using OCR to capture a screenshot and recognize Katex symbols, I must say that we currently do not see any issues with the efficiency and accuracy of the current implementation.

Our current approach of recognizing the structure of the written HTML and copying the inner HTML has been working well for us, and we have not encountered any significant performance issues. Additionally, using OCR to capture a screenshot and recognize Katex symbols may add additional complexity to the codebase and processing power, which may not be necessary at this point.

However, I appreciate your suggestion and will definitely keep it in mind as we continue to improve and optimize our implementation in the future.

Thank you again for your contribution!
