### ISSUE TITLE
ChatGPT text is not copying after plus upgrade

### ISSUE THREAD

**Issue by maheshmaddi** [SethuSenthil/Copy-for-ChatGPT#4]
I have upgraded to ChatGPT Plus member. The "Copy to clipboard" option is not visible for the responses of chatGPT4. The attached image is a reference.
![image](https://user-images.githubusercontent.com/1163940/225831036-438e2ebb-c5a7-494f-bfe7-8fdb90869eaf.png)

**Comment by SethuSenthil** [comment]
Thank you for reporting this issue! This seems like it is the same issue associated with #2 so I'll close this and continue this on the other thread!
